route:
  receiver: webhook
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  group_by: [cluster, alertname]

receivers:
  - name: webhook
    webhook_config:
      url: http://142.150.208.232:8080/alert