route:
  receiver: 'webhook'
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 5m
  group_by: ['cluster', 'alertname']

receivers:
  - name: 'webhook'
    webhook_configs:
      - url: http://142.150.208.232:8080/alert